name: Test Suite

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: "-D warnings"
  RUST_VERSION: "1.88.0"

jobs:
  lints:
    name: Tests and Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt, clippy
          toolchain: ${{ env.RUST_VERSION }}

      - name: Run cargo fmt
        run: cargo fmt --all --check

      - name: Run cargo clippy
        run: cargo clippy

      - name: Run cargo test
        run: cargo test

  build:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Build release
        run: cargo build -r
